version: "3.7"

services:

  dagyter:
    hostname: dagyter
    image: nicogalland/dagyter
    volumes:
        - ./alertes-conf:/workspace
        - ./persistance/dagster:/dagster_db/
        - ./commons_alerts.py:/python_modules/commons_alerts.py
        - ~/.ssh:/root/.ssh:ro
    ports:
      - "8502:8501"
      - "8889:8888"
      - "3001:3000"

  menu:
    hostname: menu
    image: nicogalland/cross-app-menu
    volumes:
      - ./urls.conf:/usr/share/nginx/html/environment_settings 
    ports:
      - "8080:80"

